<?php

/**
 * This is the model base class for the table "inst_nivel_establecimiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NivelEstablecimiento".
 *
 * Columns in table "inst_nivel_establecimiento" available as properties of the model,
 * followed by relations of table "inst_nivel_establecimiento" available as properties of the model.
 *
 * @property integer $id
 * @property integer $nivelID
 * @property integer $establecimientoID
 *
 * @property InstEstablecimiento $establecimiento
 * @property InstNivel $nivel
 */
abstract class BaseNivelEstablecimiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_nivel_establecimiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NivelEstablecimiento|NivelEstablecimientos', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('nivelID, establecimientoID', 'numerical', 'integerOnly'=>true),
			array('nivelID, establecimientoID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nivelID, establecimientoID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'establecimiento' => array(self::BELONGS_TO, 'InstEstablecimiento', 'establecimientoID'),
			'nivel' => array(self::BELONGS_TO, 'InstNivel', 'nivelID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nivelID' => null,
			'establecimientoID' => null,
			'establecimiento' => null,
			'nivel' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nivelID', $this->nivelID);
		$criteria->compare('establecimientoID', $this->establecimientoID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}