<?php

/**
 * This is the model base class for the table "inst_nivel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Nivel".
 *
 * Columns in table "inst_nivel" available as properties of the model,
 * followed by relations of table "inst_nivel" available as properties of the model.
 *
 * @property integer $id
 * @property string $nivel
 *
 * @property InstNivelEstablecimiento[] $instNivelEstablecimientos
 */
abstract class BaseNivel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_nivel';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Nivel|Nivels', $n);
	}

	public static function representingColumn() {
		return 'nivel';
	}

	public function rules() {
		return array(
			array('nivel', 'length', 'max'=>100),
			array('nivel', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nivel', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instNivelEstablecimientos' => array(self::HAS_MANY, 'InstNivelEstablecimiento', 'nivelID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nivel' => Yii::t('app', 'Nivel'),
			'instNivelEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nivel', $this->nivel, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}