<?php

/**
 * This is the model base class for the table "inst_jornada_establecimiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Jornadaestablecimiento".
 *
 * Columns in table "inst_jornada_establecimiento" available as properties of the model,
 * followed by relations of table "inst_jornada_establecimiento" available as properties of the model.
 *
 * @property integer $id
 * @property integer $establecimientoID
 * @property integer $jornadaID
 *
 * @property InstEstablecimiento $establecimiento
 * @property InstJornada $jornada
 */
abstract class BaseJornadaestablecimiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_jornada_establecimiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Jornadaestablecimiento|Jornadaestablecimientos', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('establecimientoID, jornadaID', 'numerical', 'integerOnly'=>true),
			array('establecimientoID, jornadaID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, establecimientoID, jornadaID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'establecimiento' => array(self::BELONGS_TO, 'InstEstablecimiento', 'establecimientoID'),
			'jornada' => array(self::BELONGS_TO, 'InstJornada', 'jornadaID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'establecimientoID' => null,
			'jornadaID' => null,
			'establecimiento' => null,
			'jornada' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('establecimientoID', $this->establecimientoID);
		$criteria->compare('jornadaID', $this->jornadaID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}