<?php

/**
 * This is the model base class for the table "inst_capacidadexcepcional_establecimiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Capacidadexcepcionalestablecimiento".
 *
 * Columns in table "inst_capacidadexcepcional_establecimiento" available as properties of the model,
 * followed by relations of table "inst_capacidadexcepcional_establecimiento" available as properties of the model.
 *
 * @property integer $id
 * @property integer $capacidadexcepcionalID
 * @property integer $establecimientoID
 *
 * @property InstCapacidadexcepcional $capacidadexcepcional
 * @property InstEstablecimiento $establecimiento
 */
abstract class BaseCapacidadexcepcionalestablecimiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_capacidadexcepcional_establecimiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Capacidadexcepcionalestablecimiento|Capacidadexcepcionalestablecimientos', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('capacidadexcepcionalID, establecimientoID', 'numerical', 'integerOnly'=>true),
			array('capacidadexcepcionalID, establecimientoID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, capacidadexcepcionalID, establecimientoID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'capacidadexcepcional' => array(self::BELONGS_TO, 'InstCapacidadexcepcional', 'capacidadexcepcionalID'),
			'establecimiento' => array(self::BELONGS_TO, 'InstEstablecimiento', 'establecimientoID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'capacidadexcepcionalID' => null,
			'establecimientoID' => null,
			'capacidadexcepcional' => null,
			'establecimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('capacidadexcepcionalID', $this->capacidadexcepcionalID);
		$criteria->compare('establecimientoID', $this->establecimientoID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}