<?php

/**
 * This is the model base class for the table "tipodiscapacidad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tipodiscapacidad".
 *
 * Columns in table "tipodiscapacidad" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idtipoDiscapacidad
 * @property integer $codigo
 * @property string $descripcion
 *
 */
abstract class BaseTipodiscapacidad extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipodiscapacidad';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tipodiscapacidad|Tipodiscapacidads', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('codigo, descripcion', 'required'),
			array('codigo', 'numerical', 'integerOnly'=>true),
			array('descripcion', 'length', 'max'=>255),
			array('idtipoDiscapacidad, codigo, descripcion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
                    'egresados' => array(self::HAS_MANY, 'Egresado', 'TIPO_DISCAPACIDAD'),
                    
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idtipoDiscapacidad' => Yii::t('app', 'Idtipo Discapacidad'),
			'codigo' => Yii::t('app', 'Codigo'),
			'descripcion' => Yii::t('app', 'Descripcion'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idtipoDiscapacidad', $this->idtipoDiscapacidad);
		$criteria->compare('codigo', $this->codigo);
		$criteria->compare('descripcion', $this->descripcion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}