<?php

/**
 * This is the model base class for the table "inst_jornada".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Jornada".
 *
 * Columns in table "inst_jornada" available as properties of the model,
 * followed by relations of table "inst_jornada" available as properties of the model.
 *
 * @property integer $id
 * @property string $tipojornada
 *
 * @property InstJornadaEstablecimiento[] $instJornadaEstablecimientos
 */
abstract class BaseJornada extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_jornada';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Jornada|Jornadas', $n);
	}

	public static function representingColumn() {
		return 'tipojornada';
	}

	public function rules() {
		return array(
			array('tipojornada', 'length', 'max'=>60),
			array('tipojornada', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, tipojornada', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instJornadaEstablecimientos' => array(self::HAS_MANY, 'InstJornadaEstablecimiento', 'jornadaID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tipojornada' => Yii::t('app', 'Tipojornada'),
			'instJornadaEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('tipojornada', $this->tipojornada, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}