<?php

/**
 * This is the model base class for the table "historicoegresado".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Historicoegresado".
 *
 * Columns in table "historicoegresado" available as properties of the model,
 * followed by relations of table "historicoegresado" available as properties of the model.
 *
 * @property integer $id
 * @property integer $egresadoID
 * @property integer $sedeID
 * @property string $grado
 * @property string $anio

 *
 * @property Areaconocimiento[] $areaconocimientos
 * @property EstudEgresado $egresado
 * @property SedSede $sede
 */
abstract class BaseHistoricoegresado extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'historicoegresado';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Historicoegresado|Historicoegresados', $n);
	}

	public static function representingColumn() {
		return 'grado';
	}

	public function rules() {
		return array(
                       array('grado+anio','application.extensions.uniqueMultiColumnValidator'), 
			array('egresadoID, sedeID', 'numerical', 'integerOnly'=>true),
			array('grado', 'length', 'max'=>2),
			//array('anio', 'safe'),
			array('egresadoID, sedeID, grado, anio', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, egresadoID, sedeID, grado, anio', 'safe', 'on'=>'search'), 
                        array('anio+grado+egresadoID','application.extensions.uniqueMultiColumnValidator'), 
		); 
	}

	public function relations() {
		return array(
			'areaconocimientos' => array(self::HAS_MANY, 'Areaconocimiento', 'historicoegresadoID'),
			'egresado' => array(self::BELONGS_TO, 'EstudEgresado', 'egresadoID'),
			'sede' => array(self::BELONGS_TO, 'SedSede', 'sedeID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'egresadoID' => null,
			'sedeID' => null,
			'grado' => Yii::t('app', 'Grado'),
			'anio' => Yii::t('app', 'Año'),
			
			'areaconocimientos' => null,
			'egresado' => null,
			'sede' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('egresadoID', $this->egresadoID);
		$criteria->compare('sedeID', $this->sedeID);
		$criteria->compare('grado', $this->grado, true);
		$criteria->compare('anio', $this->anio, true);
		

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}