<?php

/**
 * This is the model base class for the table "historicolaboral".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Historicolaboral".
 *
 * Columns in table "historicolaboral" available as properties of the model,
 * followed by relations of table "historicolaboral" available as properties of the model.
 *
 * @property integer $id
 * @property string $vinculacion
 * @property string $fechainicio
 * @property string $fechafin
 * @property string $municipio
 * @property string $empresa
 * @property string $sector
 * @property string $cargo
 * @property double $honorariosSMMLV
 * @property integer $egresadoID
 * @property integer $empresaID
 *
 * @property Empresa $empresa0
 */
abstract class BaseHistoricolaboral extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'historicolaboral';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Historicolaboral|Historicolaborals', $n);
	}

	public static function representingColumn() {
		return 'vinculacion';
	}

	public function rules() {
		return array(
			array('egresadoID, empresaID', 'numerical', 'integerOnly'=>true),
			array('honorariosSMMLV', 'numerical'),
			array('vinculacion, sector, cargo', 'length', 'max'=>20),
			array('municipio, empresa', 'length', 'max'=>30),
			array('fechainicio, fechafin', 'safe'),
			array('vinculacion, fechainicio, fechafin, municipio, empresa, sector, cargo, honorariosSMMLV, egresadoID, empresaID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, vinculacion, fechainicio, fechafin, municipio, empresa, sector, cargo, honorariosSMMLV, egresadoID, empresaID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empresa0' => array(self::BELONGS_TO, 'Empresa', 'empresaID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'vinculacion' => Yii::t('app', 'Vinculación'),
			'fechainicio' => Yii::t('app', 'Fecha inicio'),
			'fechafin' => Yii::t('app', 'Fecha fin'),
			'municipio' => Yii::t('app', 'Municipio'),
			'empresa' => Yii::t('app', 'Empresa'),
			'sector' => Yii::t('app', 'Sector'),
			'cargo' => Yii::t('app', 'Cargo'),
			'honorariosSMMLV' => Yii::t('app', 'Honorarios Smmlv'),
			'egresadoID' => Yii::t('app', 'Egresado'),
			'empresaID' => null,
			'empresa0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('vinculacion', $this->vinculacion, true);
		$criteria->compare('fechainicio', $this->fechainicio, true);
		$criteria->compare('fechafin', $this->fechafin, true);
		$criteria->compare('municipio', $this->municipio, true);
		$criteria->compare('empresa', $this->empresa, true);
		$criteria->compare('sector', $this->sector, true);
		$criteria->compare('cargo', $this->cargo, true);
		$criteria->compare('honorariosSMMLV', $this->honorariosSMMLV);
		$criteria->compare('egresadoID', $this->egresadoID);
		$criteria->compare('empresaID', $this->empresaID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}