<?php

/**
 * This is the model base class for the table "inst_modeloseducativos_establecimiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Modeloseducativosestablecimiento".
 *
 * Columns in table "inst_modeloseducativos_establecimiento" available as properties of the model,
 * followed by relations of table "inst_modeloseducativos_establecimiento" available as properties of the model.
 *
 * @property integer $id
 * @property integer $modeloseducativosID
 * @property integer $establecimientoID
 *
 * @property InstEstablecimiento $establecimiento
 * @property InstModeloseducativos $modeloseducativos
 */
abstract class BaseModeloseducativosestablecimiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_modeloseducativos_establecimiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Modeloseducativosestablecimiento|Modeloseducativosestablecimientos', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('modeloseducativosID, establecimientoID', 'numerical', 'integerOnly'=>true),
			array('modeloseducativosID, establecimientoID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, modeloseducativosID, establecimientoID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'establecimiento' => array(self::BELONGS_TO, 'InstEstablecimiento', 'establecimientoID'),
			'modeloseducativos' => array(self::BELONGS_TO, 'InstModeloseducativos', 'modeloseducativosID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'modeloseducativosID' => null,
			'establecimientoID' => null,
			'establecimiento' => null,
			'modeloseducativos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('modeloseducativosID', $this->modeloseducativosID);
		$criteria->compare('establecimientoID', $this->establecimientoID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}