<?php

/**
 * This is the model base class for the table "inst_capacidadexcepcional".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Capacidadexcepcional".
 *
 * Columns in table "inst_capacidadexcepcional" available as properties of the model,
 * followed by relations of table "inst_capacidadexcepcional" available as properties of the model.
 *
 * @property integer $id
 * @property string $capacidadexcepcional
 *
 * @property InstCapacidadexcepcionalEstablecimiento[] $instCapacidadexcepcionalEstablecimientos
 */
abstract class BaseCapacidadexcepcional extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_capacidadexcepcional';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Capacidadexcepcional|Capacidadexcepcionals', $n);
	}

	public static function representingColumn() {
		return 'capacidadexcepcional';
	}

	public function rules() {
		return array(
			array('capacidadexcepcional', 'length', 'max'=>70),
			array('capacidadexcepcional', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, capacidadexcepcional', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instCapacidadexcepcionalEstablecimientos' => array(self::HAS_MANY, 'InstCapacidadexcepcionalEstablecimiento', 'capacidadexcepcionalID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'capacidadexcepcional' => Yii::t('app', 'Capacidadexcepcional'),
			'instCapacidadexcepcionalEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('capacidadexcepcional', $this->capacidadexcepcional, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}