<?php

/**
 * This is the model base class for the table "inst_discapacidad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Discapacidad".
 *
 * Columns in table "inst_discapacidad" available as properties of the model,
 * followed by relations of table "inst_discapacidad" available as properties of the model.
 *
 * @property integer $id
 * @property string $discapacidad
 *
 * @property InstDiscapacidadEstablecimiento[] $instDiscapacidadEstablecimientos
 */
abstract class BaseDiscapacidad extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_discapacidad';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Discapacidad|Discapacidads', $n);
	}

	public static function representingColumn() {
		return 'discapacidad';
	}

	public function rules() {
		return array(
			array('discapacidad', 'length', 'max'=>60),
			array('discapacidad', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, discapacidad', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instDiscapacidadEstablecimientos' => array(self::HAS_MANY, 'InstDiscapacidadEstablecimiento', 'discapacidadID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'discapacidad' => Yii::t('app', 'Discapacidad'),
			'instDiscapacidadEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('discapacidad', $this->discapacidad, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}