<?php

/**
 * This is the model base class for the table "inst_idioma_establecimiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Idiomaestablecimiento".
 *
 * Columns in table "inst_idioma_establecimiento" available as properties of the model,
 * followed by relations of table "inst_idioma_establecimiento" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idiomaID
 * @property integer $establecimientoID
 *
 * @property InstIdioma $idioma
 * @property InstEstablecimiento $establecimiento
 */
abstract class BaseIdiomaestablecimiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_idioma_establecimiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Idiomaestablecimiento|Idiomaestablecimientos', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('idiomaID, establecimientoID', 'numerical', 'integerOnly'=>true),
			array('idiomaID, establecimientoID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idiomaID, establecimientoID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idioma' => array(self::BELONGS_TO, 'InstIdioma', 'idiomaID'),
			'establecimiento' => array(self::BELONGS_TO, 'InstEstablecimiento', 'establecimientoID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idiomaID' => null,
			'establecimientoID' => null,
			'idioma' => null,
			'establecimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idiomaID', $this->idiomaID);
		$criteria->compare('establecimientoID', $this->establecimientoID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}