<?php

/**
 * This is the model base class for the table "inst_modeloseducativos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Modeloseducativos".
 *
 * Columns in table "inst_modeloseducativos" available as properties of the model,
 * followed by relations of table "inst_modeloseducativos" available as properties of the model.
 *
 * @property integer $id
 * @property string $modeloseducativos
 *
 * @property InstModeloseducativosEstablecimiento[] $instModeloseducativosEstablecimientos
 */
abstract class BaseModeloseducativos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_modeloseducativos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Modeloseducativos|Modeloseducativoses', $n);
	}

	public static function representingColumn() {
		return 'modeloseducativos';
	}

	public function rules() {
		return array(
			array('modeloseducativos', 'length', 'max'=>100),
			array('modeloseducativos', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, modeloseducativos', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instModeloseducativosEstablecimientos' => array(self::HAS_MANY, 'InstModeloseducativosEstablecimiento', 'modeloseducativosID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'modeloseducativos' => Yii::t('app', 'Modeloseducativos'),
			'instModeloseducativosEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('modeloseducativos', $this->modeloseducativos, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}