<?php

/**
 * This is the model base class for the table "egresado".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Egresado".
 *
 * Columns in table "egresado" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $CODIGO_SED
 * @property string $ID
 * @property string $MUN_CODIGO
 * @property string $CODIGO_DANE_ESTABLEDUCATIVO
 * @property string $CODIGO_DANE_SEDE
 * @property string $CONS_SEDE
 
 * @property string $TIPO_DOCUMENTO
 * @property string $NRO_OCUMENTO
 * @property string $EXPEDICION_DOC_DPTO
 * @property string $EXPEDICION_DOC_MUN
 * @property string $APELLIDO1
 * @property string $APELLIDO2
 * @property string $NOMBRE1
 * @property string $NOMBRE2
 * @property string $FechaNacDate
 * @property string $DEPARTAMENTO_NACIMIENTO
 * @property string $MUNICIPIO_NACIMIENTO
 * @property string $GENERO
 * @property string $ZONA_RESIDENCIA_ESTUDIANTE
 * @property string $DIRECCION_RESIDENCIA
 * @property string $TEL
 * @property string $RESIDENCIA_DEPARTAMENTO
 * @property string $RESIDENCIA_MUNICIPIO
 * @property string $ESTRATO
 * @property string $SISBEN
 * @property string $POB_VICT_CONF
 * @property string $DPTO_EXP
 * @property string $MUN_EXP
 * @property string $PROVIENE_OTRO_MUN
 * @property string $TIPO_DISCAPACIDAD
 * @property string $CAPACIDADES_EXCEPCIONALES
 * @property string $ETNIA
 * @property string $INS_FAMILIAR
 * @property string $CARACTER
 * @property string $ESPECIALIDAD

 
 * @property integer $Grupo_id
 * @property string $SUBSIDIADO
 * @property string $REPITENTE
 * @property string $NUEVO
 * @property string $SIT_ACAD_ANO_ANT
 * @property string $CON_ALUM_ANO_ANT
 * @property string $ID_ALUMNO
 
 * @property string $NOMBRE1_FON
 * @property string $NOMBRE2_FON
 * @property string $APELLIDO1_FON
 * @property string $APELLIDO2_FON
 * @property string $PER_ID
 
 

 * @property string $BUENO
 * @property string $CAR_ID
 
 * @property string $NOMBRE_ESTABLECIMIENTO
 
 * @property string $NOMBRE_SEDE
 
 * @property string $DISCAP1
 
 * @property string $COD_MUN1
 *
 */
abstract class BaseEgresado extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'egresado';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Egresado|Egresados', $n);
	}

	public static function representingColumn() {
		return 'CODIGO_SED';
	}

	public function rules() {
		return array(
                        array('FACEBOOK, TWITTER, LINKEDIN', 'email'),
			array('Grupo_id, CELULAR', 'numerical', 'integerOnly'=>true),
			array('CODIGO_SED, PER_ID, CAR_ID,   COD_MUN1', 'length', 'max'=>10),
			array('ID', 'length', 'max'=>16),
			array('MUN_CODIGO, TIPO_DOCUMENTO, EXPEDICION_DOC_MUN, DEPARTAMENTO_NACIMIENTO, MUNICIPIO_NACIMIENTO, RESIDENCIA_DEPARTAMENTO, RESIDENCIA_MUNICIPIO, DPTO_EXP, MUN_EXP,  BUENO', 'length', 'max'=>20),
			array('CODIGO_DANE_ESTABLEDUCATIVO, CODIGO_DANE_SEDE', 'length', 'max'=>12),
			array('CONS_SEDE', 'length', 'max'=>18),
			array('NRO_OCUMENTO', 'length', 'max'=>20),
                        array('FACEBOOK, TWITTER,LINKEDIN','length', 'max'=>40),
			array('EXPEDICION_DOC_DPTO', 'length', 'max'=>20),
			array('APELLIDO1, APELLIDO2, NOMBRE1, NOMBRE2, DIRECCION_RESIDENCIA, TEL', 'length', 'max'=>200),
			array('GENERO', 'length', 'max'=>10),
			array('ZONA_RESIDENCIA_ESTUDIANTE, ESTRATO, SISBEN, POB_VICT_CONF, PROVIENE_OTRO_MUN, TIPO_DISCAPACIDAD, CAPACIDADES_EXCEPCIONALES,  ESPECIALIDAD,  DISCAP1', 'length', 'max'=>150),
			array('ETNIA, SUBSIDIADO, REPITENTE, NUEVO, SIT_ACAD_ANO_ANT, CON_ALUM_ANO_ANT', 'length', 'max'=>20),
			array('INS_FAMILIAR,  NOMBRE1_FON, NOMBRE2_FON, APELLIDO1_FON, APELLIDO2_FON', 'length', 'max'=>100),
			array('ID_ALUMNO', 'length', 'max'=>30),
			array('NOMBRE_ESTABLECIMIENTO, NOMBRE_SEDE', 'length', 'max'=>255),
			array('FechaNacDate', 'safe'),
			array('CODIGO_SED, ID, MUN_CODIGO, CODIGO_DANE_ESTABLEDUCATIVO, CODIGO_DANE_SEDE, CONS_SEDE, TIPO_DOCUMENTO, NRO_OCUMENTO, EXPEDICION_DOC_DPTO, EXPEDICION_DOC_MUN, APELLIDO1, APELLIDO2, NOMBRE1, NOMBRE2, FechaNacDate, DEPARTAMENTO_NACIMIENTO, MUNICIPIO_NACIMIENTO, GENERO, ZONA_RESIDENCIA_ESTUDIANTE, DIRECCION_RESIDENCIA, TEL, RESIDENCIA_DEPARTAMENTO, RESIDENCIA_MUNICIPIO, ESTRATO, SISBEN, POB_VICT_CONF, DPTO_EXP, MUN_EXP, PROVIENE_OTRO_MUN, TIPO_DISCAPACIDAD, CAPACIDADES_EXCEPCIONALES, ETNIA, INS_FAMILIAR, ESPECIALIDAD,  Grupo_id, SUBSIDIADO, REPITENTE, NUEVO, SIT_ACAD_ANO_ANT, CON_ALUM_ANO_ANT, ID_ALUMNO, NOMBRE1_FON, NOMBRE2_FON, APELLIDO1_FON, APELLIDO2_FON, PER_ID,   BUENO, CAR_ID, NOMBRE_ESTABLECIMIENTO,  NOMBRE_SEDE,  DISCAP1,  COD_MUN1', 'default', 'setOnEmpty' => true, 'value' => null),
			array('CODIGO_SED, ID, MUN_CODIGO, CODIGO_DANE_ESTABLEDUCATIVO, CODIGO_DANE_SEDE, CONS_SEDE, TIPO_DOCUMENTO, NRO_OCUMENTO, EXPEDICION_DOC_DPTO, EXPEDICION_DOC_MUN, APELLIDO1, APELLIDO2, NOMBRE1, NOMBRE2, FechaNacDate, DEPARTAMENTO_NACIMIENTO, MUNICIPIO_NACIMIENTO, GENERO, ZONA_RESIDENCIA_ESTUDIANTE, DIRECCION_RESIDENCIA, TEL, RESIDENCIA_DEPARTAMENTO, RESIDENCIA_MUNICIPIO, ESTRATO, SISBEN, POB_VICT_CONF, DPTO_EXP, MUN_EXP, PROVIENE_OTRO_MUN, TIPO_DISCAPACIDAD, CAPACIDADES_EXCEPCIONALES, ETNIA, INS_FAMILIAR,  ESPECIALIDAD,   Grupo_id, SUBSIDIADO, REPITENTE, NUEVO, SIT_ACAD_ANO_ANT, CON_ALUM_ANO_ANT, ID_ALUMNO, NOMBRE1_FON, NOMBRE2_FON, APELLIDO1_FON, APELLIDO2_FON, PER_ID,  BUENO, CAR_ID, NOMBRE_ESTABLECIMIENTO,  NOMBRE_SEDE,  DISCAP1,  COD_MUN1', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
                    'tIPODISCAPACIDAD' => array(self::BELONGS_TO, 'Tipodiscapacidad', 'TIPO_DISCAPACIDAD'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'CODIGO_SED' => Yii::t('app', 'Cod. Sede'),
			'ID' => Yii::t('app', 'ID'),
			'MUN_CODIGO' => Yii::t('app', 'Cod. municipio'),
			'CODIGO_DANE_ESTABLEDUCATIVO' => Yii::t('app', 'Cod. Dane E.E.'),
			'CODIGO_DANE_SEDE' => Yii::t('app', 'Cod. Dane Sede'),
			'CONS_SEDE' => Yii::t('app', 'Cons Sede'),
			
			'TIPO_DOCUMENTO' => Yii::t('app', 'Tipo Documento'),
			'NRO_OCUMENTO' => Yii::t('app', 'Nro documento'),
			'EXPEDICION_DOC_DPTO' => Yii::t('app', 'Expedicion Doc. Dpto'),
			'EXPEDICION_DOC_MUN' => Yii::t('app', 'Expedicion Doc Municipio'),
			'APELLIDO1' => Yii::t('app', 'Apellido 1'),
			'APELLIDO2' => Yii::t('app', 'Apellido 2'),
			'NOMBRE1' => Yii::t('app', 'Nombre 1'),
			'NOMBRE2' => Yii::t('app', 'Nombre 2'),
			'FechaNacDate' => Yii::t('app', 'Fecha Nacimiento'),
			'DEPARTAMENTO_NACIMIENTO' => Yii::t('app', 'Depto. Nacimiento'),
			'MUNICIPIO_NACIMIENTO' => Yii::t('app', 'Municipio Nacimiento'),
			'GENERO' => Yii::t('app', 'Genero'),
			'ZONA_RESIDENCIA_ESTUDIANTE' => Yii::t('app', 'Zona Residencia Estudiante'),
			'DIRECCION_RESIDENCIA' => Yii::t('app', 'Direccion Residencia'),
			'TEL' => Yii::t('app', 'Tel'),
			'RESIDENCIA_DEPARTAMENTO' => Yii::t('app', 'Residencia Departamento'),
			'RESIDENCIA_MUNICIPIO' => Yii::t('app', 'Residencia Municipio'),
			'ESTRATO' => Yii::t('app', 'Estrato'),
			'SISBEN' => Yii::t('app', 'Sisben'),
			'POB_VICT_CONF' => Yii::t('app', 'Pob Vict Conf'),
			'DPTO_EXP' => Yii::t('app', 'Dpto Exp'),
			'MUN_EXP' => Yii::t('app', 'Mun Exp'),
			'PROVIENE_OTRO_MUN' => Yii::t('app', 'Proviene Otro Mun'),
			'TIPO_DISCAPACIDAD' => Yii::t('app', 'Tipo Discapacidad'),
			'CAPACIDADES_EXCEPCIONALES' => Yii::t('app', 'Capacidades Excepcionales'),
			'ETNIA' => Yii::t('app', 'Etnia'),
			'INS_FAMILIAR' => Yii::t('app', 'Ins Familiar'),
			'ESPECIALIDAD' => Yii::t('app', 'Especialidad'),
			'Grupo_id' => Yii::t('app', 'Grupo'),
			'SUBSIDIADO' => Yii::t('app', 'Subsidiado'),
			'REPITENTE' => Yii::t('app', 'Repitente'),
			'NUEVO' => Yii::t('app', 'Nuevo'),
			'SIT_ACAD_ANO_ANT' => Yii::t('app', 'Sit Acad Ano Ant'),
			'CON_ALUM_ANO_ANT' => Yii::t('app', 'Con Alum Ano Ant'),
			'ID_ALUMNO' => Yii::t('app', 'Id Alumno'),
			'NOMBRE1_FON' => Yii::t('app', 'Nombre1 Fon'),
			'NOMBRE2_FON' => Yii::t('app', 'Nombre2 Fon'),
			'APELLIDO1_FON' => Yii::t('app', 'Apellido1 Fon'),
			'APELLIDO2_FON' => Yii::t('app', 'Apellido2 Fon'),
			'PER_ID' => Yii::t('app', 'Per'),
			'BUENO' => Yii::t('app', 'Bueno'),
			'CAR_ID' => Yii::t('app', 'Car'),
			'NOMBRE_ESTABLECIMIENTO' => Yii::t('app', 'Nombre Establecimiento'),
			'NOMBRE_SEDE' => Yii::t('app', 'Nombre Sede'),
			'DISCAP1' => Yii::t('app', 'Discap1'),
			'COD_MUN1' => Yii::t('app', 'Cod Mun1'),
                        'FACEBOOK' => Yii::t('app','Facebook'),
                        'TWITTER' => Yii::t('app','Twitter'),
                        'LINKEDIN' => Yii::t('app','LinkedIn'),
                        'CELULAR' => Yii::t('app','Celular'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
                
		$criteria->compare('CODIGO_SED', $this->CODIGO_SED, true);
		$criteria->compare('ID', $this->ID, true);
		$criteria->compare('MUN_CODIGO', $this->MUN_CODIGO, true);
		$criteria->compare('CODIGO_DANE_ESTABLEDUCATIVO', $this->CODIGO_DANE_ESTABLEDUCATIVO, true);
		$criteria->compare('CODIGO_DANE_SEDE', $this->CODIGO_DANE_SEDE, true);
		$criteria->compare('CONS_SEDE', $this->CONS_SEDE, true);
		
		$criteria->compare('TIPO_DOCUMENTO', $this->TIPO_DOCUMENTO, true);
		$criteria->compare('NRO_OCUMENTO', $this->NRO_OCUMENTO, true);
		$criteria->compare('EXPEDICION_DOC_DPTO', $this->EXPEDICION_DOC_DPTO, true);
		$criteria->compare('EXPEDICION_DOC_MUN', $this->EXPEDICION_DOC_MUN, true);
		$criteria->compare('APELLIDO1', $this->APELLIDO1, true);
		$criteria->compare('APELLIDO2', $this->APELLIDO2, true);
		$criteria->compare('NOMBRE1', $this->NOMBRE1, true);
		$criteria->compare('NOMBRE2', $this->NOMBRE2, true);
		$criteria->compare('FechaNacDate', $this->FechaNacDate, true);
		$criteria->compare('DEPARTAMENTO_NACIMIENTO', $this->DEPARTAMENTO_NACIMIENTO, true);
		$criteria->compare('MUNICIPIO_NACIMIENTO', $this->MUNICIPIO_NACIMIENTO, true);
		$criteria->compare('GENERO', $this->GENERO, true);
		$criteria->compare('ZONA_RESIDENCIA_ESTUDIANTE', $this->ZONA_RESIDENCIA_ESTUDIANTE, true);
		$criteria->compare('DIRECCION_RESIDENCIA', $this->DIRECCION_RESIDENCIA, true);
		$criteria->compare('TEL', $this->TEL, true);
		$criteria->compare('RESIDENCIA_DEPARTAMENTO', $this->RESIDENCIA_DEPARTAMENTO, true);
		$criteria->compare('RESIDENCIA_MUNICIPIO', $this->RESIDENCIA_MUNICIPIO, true);
		$criteria->compare('ESTRATO', $this->ESTRATO, true);
		$criteria->compare('SISBEN', $this->SISBEN, true);
		$criteria->compare('POB_VICT_CONF', $this->POB_VICT_CONF, true);
		$criteria->compare('DPTO_EXP', $this->DPTO_EXP, true);
		$criteria->compare('MUN_EXP', $this->MUN_EXP, true);
		$criteria->compare('PROVIENE_OTRO_MUN', $this->PROVIENE_OTRO_MUN, true);
		$criteria->compare('TIPO_DISCAPACIDAD', $this->TIPO_DISCAPACIDAD, true);
		$criteria->compare('CAPACIDADES_EXCEPCIONALES', $this->CAPACIDADES_EXCEPCIONALES, true);
		$criteria->compare('ETNIA', $this->ETNIA, true);
		$criteria->compare('INS_FAMILIAR', $this->INS_FAMILIAR, true);
		$criteria->compare('ESPECIALIDAD', $this->ESPECIALIDAD, true);
		$criteria->compare('Grupo_id', $this->Grupo_id);
		$criteria->compare('SUBSIDIADO', $this->SUBSIDIADO, true);
		$criteria->compare('REPITENTE', $this->REPITENTE, true);
		$criteria->compare('NUEVO', $this->NUEVO, true);
		$criteria->compare('SIT_ACAD_ANO_ANT', $this->SIT_ACAD_ANO_ANT, true);
		$criteria->compare('CON_ALUM_ANO_ANT', $this->CON_ALUM_ANO_ANT, true);
		$criteria->compare('ID_ALUMNO', $this->ID_ALUMNO, true);
		$criteria->compare('NOMBRE1_FON', $this->NOMBRE1_FON, true);
		$criteria->compare('NOMBRE2_FON', $this->NOMBRE2_FON, true);
		$criteria->compare('APELLIDO1_FON', $this->APELLIDO1_FON, true);
		$criteria->compare('APELLIDO2_FON', $this->APELLIDO2_FON, true);
		$criteria->compare('PER_ID', $this->PER_ID, true);
		$criteria->compare('BUENO', $this->BUENO, true);
		$criteria->compare('CAR_ID', $this->CAR_ID, true);
		$criteria->compare('NOMBRE_ESTABLECIMIENTO', $this->NOMBRE_ESTABLECIMIENTO, true);
		$criteria->compare('NOMBRE_SEDE', $this->NOMBRE_SEDE, true);
		$criteria->compare('DISCAP1', $this->DISCAP1, true);
		$criteria->compare('COD_MUN1', $this->COD_MUN1, true);
                
                $criteria->compare('FACEBOOK', $this->FACEBOOK, true);
		$criteria->compare('TWITTER', $this->TWITTER, true);
		$criteria->compare('LINKEDIN', $this->LINKEDIN, true);
		$criteria->compare('CELULAR', $this->CELULAR, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        
        public function busqueda() {
		$criteria = new CDbCriteria;
                //$criteria->compare('idinscripcion', $this->idinscripcion);
		//$criteria->compare('tipo_documento_id', $this->tipo_documento_id);
		$criteria->compare('NRO_OCUMENTO', $this->NRO_OCUMENTO, true);
                $criteria->compare('APELLIDO1', $this->APELLIDO1, true);
		$criteria->compare('APELLIDO2', $this->APELLIDO2, true);
		$criteria->compare('NOMBRE1', $this->NOMBRE1, true);
		$criteria->compare('NOMBRE2', $this->NOMBRE2, true);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria
		));
        }
        
//        public function busquedaxhistorico($idsede){
//            $criteria = new CDbCriteria;
//            $criteria->join = "JOIN historicoegresado  ON(egresado.ID=historicoegresado.egresadoID)";
//            $criteria->condition = "historicoegresado.sedeID='$idsede'";
//            echo 'DENTRO DE FUNCION';
//            return new CActiveDataProvider($this, array(
//			'criteria' => $criteria,
//		));
//        }
}