<?php

/**
 * This is the model base class for the table "inst_idioma".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Idioma".
 *
 * Columns in table "inst_idioma" available as properties of the model,
 * followed by relations of table "inst_idioma" available as properties of the model.
 *
 * @property integer $id
 * @property string $idioma
 *
 * @property InstIdiomaEstablecimiento[] $instIdiomaEstablecimientos
 */
abstract class BaseIdioma extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_idioma';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Idioma|Idiomas', $n);
	}

	public static function representingColumn() {
		return 'idioma';
	}

	public function rules() {
		return array(
			array('idioma', 'length', 'max'=>15),
			array('idioma', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idioma', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instIdiomaEstablecimientos' => array(self::HAS_MANY, 'InstIdiomaEstablecimiento', 'idiomaID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idioma' => Yii::t('app', 'Idioma'),
			'instIdiomaEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idioma', $this->idioma, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}