<?php

/**
 * This is the model base class for the table "sed_sede".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sede".
 *
 * Columns in table "sed_sede" available as properties of the model,
 * followed by relations of table "sed_sede" available as properties of the model.
 *
 * @property integer $id
 * @property string $secretaria
 * @property integer $coddepto
 * @property string $depto
 * @property integer $codmunicipio
 * @property string $nommunicipio
 * @property string $codestablecimiento
 * @property string $codsede
 * @property string $nombresede
 * @property string $zona
 * @property string $direccion
 * @property string $telefono
 * @property string $estadosede
 * @property string $nivelessede
 * @property string $modelossede
 * @property string $gradossede
 * @property integer $establecimientoID
 *
 * @property EgresadoSede[] $egresadoSedes
 * @property Historicoegresado[] $historicoegresados
 * @property InstEstablecimiento $establecimiento
 */
abstract class BaseSede extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sed_sede';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Sede|Sedes', $n);
	}

	public static function representingColumn() {
		return 'secretaria';
	}

	public function rules() {
		return array(
			array('coddepto, codmunicipio, establecimientoID', 'numerical', 'integerOnly'=>true),
			array('secretaria', 'length', 'max'=>40),
			array('depto, nommunicipio, zona, estadosede', 'length', 'max'=>20),
			array('codestablecimiento, codsede, telefono', 'length', 'max'=>15),
			array('nombresede, gradossede', 'length', 'max'=>60),
			array('direccion', 'length', 'max'=>150),
			array('nivelessede, modelossede', 'safe'),
			array('secretaria, coddepto, depto, codmunicipio, nommunicipio, codestablecimiento, codsede, nombresede, zona, direccion, telefono, estadosede, nivelessede, modelossede, gradossede, establecimientoID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, secretaria, coddepto, depto, codmunicipio, nommunicipio, codestablecimiento, codsede, nombresede, zona, direccion, telefono, estadosede, nivelessede, modelossede, gradossede, establecimientoID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'egresadoSedes' => array(self::HAS_MANY, 'EgresadoSede', 'sedeID'),
			'historicoegresados' => array(self::HAS_MANY, 'Historicoegresado', 'sedeID'),
			'establecimiento' => array(self::BELONGS_TO, 'Establecimiento', 'establecimientoID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'secretaria' => Yii::t('app', 'Secretaria'),
			'coddepto' => Yii::t('app', 'cod_Depto'),
			'depto' => Yii::t('app', 'Depto'),
			'codmunicipio' => Yii::t('app', 'Codmunicipio'),
			'nommunicipio' => Yii::t('app', 'Municipio'),
			'codestablecimiento' => Yii::t('app', 'Codigo EE'),
			'codsede' => Yii::t('app', 'Codigo sede'),
			'nombresede' => Yii::t('app', 'Nombre sede'),
			'zona' => Yii::t('app', 'Zona'),
			'direccion' => Yii::t('app', 'Direccion'),
			'telefono' => Yii::t('app', 'Telefono'),
			'estadosede' => Yii::t('app', 'Estado'),
			'nivelessede' => Yii::t('app', 'Niveles'),
			'modelossede' => Yii::t('app', 'Modelos'),
			'gradossede' => Yii::t('app', 'Grados'),
			'establecimientoID' => null,
			'egresadoSedes' => null,
			'historicoegresados' => null,
			'establecimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('secretaria', $this->secretaria, true);
		$criteria->compare('coddepto', $this->coddepto);
		$criteria->compare('depto', $this->depto, true);
		$criteria->compare('codmunicipio', $this->codmunicipio);
		$criteria->compare('nommunicipio', $this->nommunicipio, true);
		$criteria->compare('codestablecimiento', $this->codestablecimiento, true);
		$criteria->compare('codsede', $this->codsede, true);
		$criteria->compare('nombresede', $this->nombresede, true);
		$criteria->compare('zona', $this->zona, true);
		$criteria->compare('direccion', $this->direccion, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('estadosede', $this->estadosede, true);
		$criteria->compare('nivelessede', $this->nivelessede, true);
		$criteria->compare('modelossede', $this->modelossede, true);
		$criteria->compare('gradossede', $this->gradossede, true);
		$criteria->compare('establecimientoID', $this->establecimientoID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}