<?php

/**
 * This is the model base class for the table "egresado".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Egresado".
 *
 * Columns in table "egresado" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $CODIGO_SED
 * @property string $ID
 * @property string $MUN_CODIGO
 * @property string $CODIGO_DANE_ESTABLEDUCATIVO
 * @property string $CODIGO_DANE_SEDE
 * @property string $CONS_SEDE
 * @property integer $establecimiento_id
 * @property string $TIPO_DOCUMENTO
 * @property string $NRO_OCUMENTO
 * @property string $EXPEDICION_DOC_DPTO
 * @property string $EXPEDICION_DOC_MUN
 * @property string $APELLIDO1
 * @property string $APELLIDO2
 * @property string $NOMBRE1
 * @property string $NOMBRE2
 * @property string $FechaNacDate
 * @property string $DEPARTAMENTO_NACIMIENTO
 * @property string $MUNICIPIO_NACIMIENTO
 * @property string $GENERO
 * @property string $ZONA_RESIDENCIA_ESTUDIANTE
 * @property string $DIRECCION_RESIDENCIA
 * @property string $TEL
 * @property string $RESIDENCIA_DEPARTAMENTO
 * @property string $RESIDENCIA_MUNICIPIO
 * @property string $ESTRATO
 * @property string $SISBEN
 * @property string $POB_VICT_CONF
 * @property string $DPTO_EXP
 * @property string $MUN_EXP
 * @property string $PROVIENE_OTRO_MUN
 * @property string $TIPO_DISCAPACIDAD
 * @property string $CAPACIDADES_EXCEPCIONALES
 * @property string $ETNIA
 * @property string $INS_FAMILIAR
 * @property string $CARACTER
 * @property string $ESPECIALIDAD
 * @property string $GRUPO_CURSO
 * @property string $METODOLOGIA
 * @property integer $Grupo_id
 * @property string $SUBSIDIADO
 * @property string $REPITENTE
 * @property string $NUEVO
 * @property string $SIT_ACAD_ANO_ANT
 * @property string $CON_ALUM_ANO_ANT
 * @property string $ID_ALUMNO
 * @property string $COR_ID
 * @property string $CAB_FAMILIA
 * @property string $BEN_MAD_FLIA
 * @property string $BEN_VET_FP
 * @property string $BEN_HER_NAC
 * @property string $EST_ID
 * @property string $NOMBRE1_FON
 * @property string $NOMBRE2_FON
 * @property string $APELLIDO1_FON
 * @property string $APELLIDO2_FON
 * @property string $PER_ID
 * @property string $ESTADO
 * @property string $INTERNADO
 * @property string $VAL_DES_PERIODO2
 * @property string $NUM_CONVENIO
 * @property string $BUENO
 * @property string $CAR_ID
 * @property string $FEC_CREACION
 * @property string $NOMBRE_ESTABLECIMIENTO
 * @property string $CTE_ID_SECTOR
 * @property string $NOMBRE_SEDE
 * @property string $CTE_ID_ZONA
 * @property string $DISCAP1
 * @property string $grado1
 * @property string $COD_MUN1
 *
 */
abstract class BaseEgresado extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'egresado';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Egresado|Egresados', $n);
	}

	public static function representingColumn() {
		return 'CODIGO_SED';
	}

	public function rules() {
		return array(
			array('establecimiento_id, Grupo_id', 'numerical', 'integerOnly'=>true),
			array('CODIGO_SED, EST_ID, PER_ID, ESTADO, NUM_CONVENIO, CAR_ID, FEC_CREACION, CTE_ID_SECTOR, CTE_ID_ZONA, COD_MUN1', 'length', 'max'=>10),
			array('ID', 'length', 'max'=>16),
			array('MUN_CODIGO, TIPO_DOCUMENTO, EXPEDICION_DOC_MUN, DEPARTAMENTO_NACIMIENTO, MUNICIPIO_NACIMIENTO, RESIDENCIA_DEPARTAMENTO, RESIDENCIA_MUNICIPIO, DPTO_EXP, MUN_EXP, GRUPO_CURSO, VAL_DES_PERIODO2, BUENO', 'length', 'max'=>6),
			array('CODIGO_DANE_ESTABLEDUCATIVO, CODIGO_DANE_SEDE', 'length', 'max'=>12),
			array('CONS_SEDE', 'length', 'max'=>18),
			array('NRO_OCUMENTO', 'length', 'max'=>20),
			array('EXPEDICION_DOC_DPTO, INTERNADO', 'length', 'max'=>2),
			array('APELLIDO1, APELLIDO2, NOMBRE1, NOMBRE2, DIRECCION_RESIDENCIA, TEL', 'length', 'max'=>200),
			array('GENERO', 'length', 'max'=>1),
			array('ZONA_RESIDENCIA_ESTUDIANTE, ESTRATO, SISBEN, POB_VICT_CONF, PROVIENE_OTRO_MUN, TIPO_DISCAPACIDAD, CAPACIDADES_EXCEPCIONALES, CARACTER, ESPECIALIDAD, METODOLOGIA, DISCAP1', 'length', 'max'=>4),
			array('ETNIA, SUBSIDIADO, REPITENTE, NUEVO, SIT_ACAD_ANO_ANT, CON_ALUM_ANO_ANT, CAB_FAMILIA, BEN_MAD_FLIA, BEN_VET_FP, BEN_HER_NAC, grado1', 'length', 'max'=>3),
			array('INS_FAMILIAR, COR_ID, NOMBRE1_FON, NOMBRE2_FON, APELLIDO1_FON, APELLIDO2_FON', 'length', 'max'=>100),
			array('ID_ALUMNO', 'length', 'max'=>30),
			array('NOMBRE_ESTABLECIMIENTO, NOMBRE_SEDE', 'length', 'max'=>255),
			array('FechaNacDate', 'safe'),
			array('CODIGO_SED, ID, MUN_CODIGO, CODIGO_DANE_ESTABLEDUCATIVO, CODIGO_DANE_SEDE, CONS_SEDE, establecimiento_id, TIPO_DOCUMENTO, NRO_OCUMENTO, EXPEDICION_DOC_DPTO, EXPEDICION_DOC_MUN, APELLIDO1, APELLIDO2, NOMBRE1, NOMBRE2, FechaNacDate, DEPARTAMENTO_NACIMIENTO, MUNICIPIO_NACIMIENTO, GENERO, ZONA_RESIDENCIA_ESTUDIANTE, DIRECCION_RESIDENCIA, TEL, RESIDENCIA_DEPARTAMENTO, RESIDENCIA_MUNICIPIO, ESTRATO, SISBEN, POB_VICT_CONF, DPTO_EXP, MUN_EXP, PROVIENE_OTRO_MUN, TIPO_DISCAPACIDAD, CAPACIDADES_EXCEPCIONALES, ETNIA, INS_FAMILIAR, CARACTER, ESPECIALIDAD, GRUPO_CURSO, METODOLOGIA, Grupo_id, SUBSIDIADO, REPITENTE, NUEVO, SIT_ACAD_ANO_ANT, CON_ALUM_ANO_ANT, ID_ALUMNO, COR_ID, CAB_FAMILIA, BEN_MAD_FLIA, BEN_VET_FP, BEN_HER_NAC, EST_ID, NOMBRE1_FON, NOMBRE2_FON, APELLIDO1_FON, APELLIDO2_FON, PER_ID, ESTADO, INTERNADO, VAL_DES_PERIODO2, NUM_CONVENIO, BUENO, CAR_ID, FEC_CREACION, NOMBRE_ESTABLECIMIENTO, CTE_ID_SECTOR, NOMBRE_SEDE, CTE_ID_ZONA, DISCAP1, grado1, COD_MUN1', 'default', 'setOnEmpty' => true, 'value' => null),
			array('CODIGO_SED, ID, MUN_CODIGO, CODIGO_DANE_ESTABLEDUCATIVO, CODIGO_DANE_SEDE, CONS_SEDE, establecimiento_id, TIPO_DOCUMENTO, NRO_OCUMENTO, EXPEDICION_DOC_DPTO, EXPEDICION_DOC_MUN, APELLIDO1, APELLIDO2, NOMBRE1, NOMBRE2, FechaNacDate, DEPARTAMENTO_NACIMIENTO, MUNICIPIO_NACIMIENTO, GENERO, ZONA_RESIDENCIA_ESTUDIANTE, DIRECCION_RESIDENCIA, TEL, RESIDENCIA_DEPARTAMENTO, RESIDENCIA_MUNICIPIO, ESTRATO, SISBEN, POB_VICT_CONF, DPTO_EXP, MUN_EXP, PROVIENE_OTRO_MUN, TIPO_DISCAPACIDAD, CAPACIDADES_EXCEPCIONALES, ETNIA, INS_FAMILIAR, CARACTER, ESPECIALIDAD, GRUPO_CURSO, METODOLOGIA, Grupo_id, SUBSIDIADO, REPITENTE, NUEVO, SIT_ACAD_ANO_ANT, CON_ALUM_ANO_ANT, ID_ALUMNO, COR_ID, CAB_FAMILIA, BEN_MAD_FLIA, BEN_VET_FP, BEN_HER_NAC, EST_ID, NOMBRE1_FON, NOMBRE2_FON, APELLIDO1_FON, APELLIDO2_FON, PER_ID, ESTADO, INTERNADO, VAL_DES_PERIODO2, NUM_CONVENIO, BUENO, CAR_ID, FEC_CREACION, NOMBRE_ESTABLECIMIENTO, CTE_ID_SECTOR, NOMBRE_SEDE, CTE_ID_ZONA, DISCAP1, grado1, COD_MUN1', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'CODIGO_SED' => Yii::t('app', 'Codigo Sed'),
			'ID' => Yii::t('app', 'ID'),
			'MUN_CODIGO' => Yii::t('app', 'Mun Codigo'),
			'CODIGO_DANE_ESTABLEDUCATIVO' => Yii::t('app', 'Codigo Dane Estableducativo'),
			'CODIGO_DANE_SEDE' => Yii::t('app', 'Codigo Dane Sede'),
			'CONS_SEDE' => Yii::t('app', 'Cons Sede'),
			'establecimiento_id' => Yii::t('app', 'Establecimiento'),
			'TIPO_DOCUMENTO' => Yii::t('app', 'Tipo Documento'),
			'NRO_OCUMENTO' => Yii::t('app', 'Nro Ocumento'),
			'EXPEDICION_DOC_DPTO' => Yii::t('app', 'Expedicion Doc Dpto'),
			'EXPEDICION_DOC_MUN' => Yii::t('app', 'Expedicion Doc Mun'),
			'APELLIDO1' => Yii::t('app', 'Apellido1'),
			'APELLIDO2' => Yii::t('app', 'Apellido2'),
			'NOMBRE1' => Yii::t('app', 'Nombre1'),
			'NOMBRE2' => Yii::t('app', 'Nombre2'),
			'FechaNacDate' => Yii::t('app', 'Fecha Nac Date'),
			'DEPARTAMENTO_NACIMIENTO' => Yii::t('app', 'Departamento Nacimiento'),
			'MUNICIPIO_NACIMIENTO' => Yii::t('app', 'Municipio Nacimiento'),
			'GENERO' => Yii::t('app', 'Genero'),
			'ZONA_RESIDENCIA_ESTUDIANTE' => Yii::t('app', 'Zona Residencia Estudiante'),
			'DIRECCION_RESIDENCIA' => Yii::t('app', 'Direccion Residencia'),
			'TEL' => Yii::t('app', 'Tel'),
			'RESIDENCIA_DEPARTAMENTO' => Yii::t('app', 'Residencia Departamento'),
			'RESIDENCIA_MUNICIPIO' => Yii::t('app', 'Residencia Municipio'),
			'ESTRATO' => Yii::t('app', 'Estrato'),
			'SISBEN' => Yii::t('app', 'Sisben'),
			'POB_VICT_CONF' => Yii::t('app', 'Pob Vict Conf'),
			'DPTO_EXP' => Yii::t('app', 'Dpto Exp'),
			'MUN_EXP' => Yii::t('app', 'Mun Exp'),
			'PROVIENE_OTRO_MUN' => Yii::t('app', 'Proviene Otro Mun'),
			'TIPO_DISCAPACIDAD' => Yii::t('app', 'Tipo Discapacidad'),
			'CAPACIDADES_EXCEPCIONALES' => Yii::t('app', 'Capacidades Excepcionales'),
			'ETNIA' => Yii::t('app', 'Etnia'),
			'INS_FAMILIAR' => Yii::t('app', 'Ins Familiar'),
			'CARACTER' => Yii::t('app', 'Caracter'),
			'ESPECIALIDAD' => Yii::t('app', 'Especialidad'),
			'GRUPO_CURSO' => Yii::t('app', 'Grupo Curso'),
			'METODOLOGIA' => Yii::t('app', 'Metodologia'),
			'Grupo_id' => Yii::t('app', 'Grupo'),
			'SUBSIDIADO' => Yii::t('app', 'Subsidiado'),
			'REPITENTE' => Yii::t('app', 'Repitente'),
			'NUEVO' => Yii::t('app', 'Nuevo'),
			'SIT_ACAD_ANO_ANT' => Yii::t('app', 'Sit Acad Ano Ant'),
			'CON_ALUM_ANO_ANT' => Yii::t('app', 'Con Alum Ano Ant'),
			'ID_ALUMNO' => Yii::t('app', 'Id Alumno'),
			'COR_ID' => Yii::t('app', 'Cor'),
			'CAB_FAMILIA' => Yii::t('app', 'Cab Familia'),
			'BEN_MAD_FLIA' => Yii::t('app', 'Ben Mad Flia'),
			'BEN_VET_FP' => Yii::t('app', 'Ben Vet Fp'),
			'BEN_HER_NAC' => Yii::t('app', 'Ben Her Nac'),
			'EST_ID' => Yii::t('app', 'Est'),
			'NOMBRE1_FON' => Yii::t('app', 'Nombre1 Fon'),
			'NOMBRE2_FON' => Yii::t('app', 'Nombre2 Fon'),
			'APELLIDO1_FON' => Yii::t('app', 'Apellido1 Fon'),
			'APELLIDO2_FON' => Yii::t('app', 'Apellido2 Fon'),
			'PER_ID' => Yii::t('app', 'Per'),
			'ESTADO' => Yii::t('app', 'Estado'),
			'INTERNADO' => Yii::t('app', 'Internado'),
			'VAL_DES_PERIODO2' => Yii::t('app', 'Val Des Periodo2'),
			'NUM_CONVENIO' => Yii::t('app', 'Num Convenio'),
			'BUENO' => Yii::t('app', 'Bueno'),
			'CAR_ID' => Yii::t('app', 'Car'),
			'FEC_CREACION' => Yii::t('app', 'Fec Creacion'),
			'NOMBRE_ESTABLECIMIENTO' => Yii::t('app', 'Nombre Establecimiento'),
			'CTE_ID_SECTOR' => Yii::t('app', 'Cte Id Sector'),
			'NOMBRE_SEDE' => Yii::t('app', 'Nombre Sede'),
			'CTE_ID_ZONA' => Yii::t('app', 'Cte Id Zona'),
			'DISCAP1' => Yii::t('app', 'Discap1'),
			'grado1' => Yii::t('app', 'Grado1'),
			'COD_MUN1' => Yii::t('app', 'Cod Mun1'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('CODIGO_SED', $this->CODIGO_SED, true);
		$criteria->compare('ID', $this->ID, true);
		$criteria->compare('MUN_CODIGO', $this->MUN_CODIGO, true);
		$criteria->compare('CODIGO_DANE_ESTABLEDUCATIVO', $this->CODIGO_DANE_ESTABLEDUCATIVO, true);
		$criteria->compare('CODIGO_DANE_SEDE', $this->CODIGO_DANE_SEDE, true);
		$criteria->compare('CONS_SEDE', $this->CONS_SEDE, true);
		$criteria->compare('establecimiento_id', $this->establecimiento_id);
		$criteria->compare('TIPO_DOCUMENTO', $this->TIPO_DOCUMENTO, true);
		$criteria->compare('NRO_OCUMENTO', $this->NRO_OCUMENTO, true);
		$criteria->compare('EXPEDICION_DOC_DPTO', $this->EXPEDICION_DOC_DPTO, true);
		$criteria->compare('EXPEDICION_DOC_MUN', $this->EXPEDICION_DOC_MUN, true);
		$criteria->compare('APELLIDO1', $this->APELLIDO1, true);
		$criteria->compare('APELLIDO2', $this->APELLIDO2, true);
		$criteria->compare('NOMBRE1', $this->NOMBRE1, true);
		$criteria->compare('NOMBRE2', $this->NOMBRE2, true);
		$criteria->compare('FechaNacDate', $this->FechaNacDate, true);
		$criteria->compare('DEPARTAMENTO_NACIMIENTO', $this->DEPARTAMENTO_NACIMIENTO, true);
		$criteria->compare('MUNICIPIO_NACIMIENTO', $this->MUNICIPIO_NACIMIENTO, true);
		$criteria->compare('GENERO', $this->GENERO, true);
		$criteria->compare('ZONA_RESIDENCIA_ESTUDIANTE', $this->ZONA_RESIDENCIA_ESTUDIANTE, true);
		$criteria->compare('DIRECCION_RESIDENCIA', $this->DIRECCION_RESIDENCIA, true);
		$criteria->compare('TEL', $this->TEL, true);
		$criteria->compare('RESIDENCIA_DEPARTAMENTO', $this->RESIDENCIA_DEPARTAMENTO, true);
		$criteria->compare('RESIDENCIA_MUNICIPIO', $this->RESIDENCIA_MUNICIPIO, true);
		$criteria->compare('ESTRATO', $this->ESTRATO, true);
		$criteria->compare('SISBEN', $this->SISBEN, true);
		$criteria->compare('POB_VICT_CONF', $this->POB_VICT_CONF, true);
		$criteria->compare('DPTO_EXP', $this->DPTO_EXP, true);
		$criteria->compare('MUN_EXP', $this->MUN_EXP, true);
		$criteria->compare('PROVIENE_OTRO_MUN', $this->PROVIENE_OTRO_MUN, true);
		$criteria->compare('TIPO_DISCAPACIDAD', $this->TIPO_DISCAPACIDAD, true);
		$criteria->compare('CAPACIDADES_EXCEPCIONALES', $this->CAPACIDADES_EXCEPCIONALES, true);
		$criteria->compare('ETNIA', $this->ETNIA, true);
		$criteria->compare('INS_FAMILIAR', $this->INS_FAMILIAR, true);
		$criteria->compare('CARACTER', $this->CARACTER, true);
		$criteria->compare('ESPECIALIDAD', $this->ESPECIALIDAD, true);
		$criteria->compare('GRUPO_CURSO', $this->GRUPO_CURSO, true);
		$criteria->compare('METODOLOGIA', $this->METODOLOGIA, true);
		$criteria->compare('Grupo_id', $this->Grupo_id);
		$criteria->compare('SUBSIDIADO', $this->SUBSIDIADO, true);
		$criteria->compare('REPITENTE', $this->REPITENTE, true);
		$criteria->compare('NUEVO', $this->NUEVO, true);
		$criteria->compare('SIT_ACAD_ANO_ANT', $this->SIT_ACAD_ANO_ANT, true);
		$criteria->compare('CON_ALUM_ANO_ANT', $this->CON_ALUM_ANO_ANT, true);
		$criteria->compare('ID_ALUMNO', $this->ID_ALUMNO, true);
		$criteria->compare('COR_ID', $this->COR_ID, true);
		$criteria->compare('CAB_FAMILIA', $this->CAB_FAMILIA, true);
		$criteria->compare('BEN_MAD_FLIA', $this->BEN_MAD_FLIA, true);
		$criteria->compare('BEN_VET_FP', $this->BEN_VET_FP, true);
		$criteria->compare('BEN_HER_NAC', $this->BEN_HER_NAC, true);
		$criteria->compare('EST_ID', $this->EST_ID, true);
		$criteria->compare('NOMBRE1_FON', $this->NOMBRE1_FON, true);
		$criteria->compare('NOMBRE2_FON', $this->NOMBRE2_FON, true);
		$criteria->compare('APELLIDO1_FON', $this->APELLIDO1_FON, true);
		$criteria->compare('APELLIDO2_FON', $this->APELLIDO2_FON, true);
		$criteria->compare('PER_ID', $this->PER_ID, true);
		$criteria->compare('ESTADO', $this->ESTADO, true);
		$criteria->compare('INTERNADO', $this->INTERNADO, true);
		$criteria->compare('VAL_DES_PERIODO2', $this->VAL_DES_PERIODO2, true);
		$criteria->compare('NUM_CONVENIO', $this->NUM_CONVENIO, true);
		$criteria->compare('BUENO', $this->BUENO, true);
		$criteria->compare('CAR_ID', $this->CAR_ID, true);
		$criteria->compare('FEC_CREACION', $this->FEC_CREACION, true);
		$criteria->compare('NOMBRE_ESTABLECIMIENTO', $this->NOMBRE_ESTABLECIMIENTO, true);
		$criteria->compare('CTE_ID_SECTOR', $this->CTE_ID_SECTOR, true);
		$criteria->compare('NOMBRE_SEDE', $this->NOMBRE_SEDE, true);
		$criteria->compare('CTE_ID_ZONA', $this->CTE_ID_ZONA, true);
		$criteria->compare('DISCAP1', $this->DISCAP1, true);
		$criteria->compare('grado1', $this->grado1, true);
		$criteria->compare('COD_MUN1', $this->COD_MUN1, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}