<?php

/**
 * This is the model base class for the table "adm_usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "adm_usuario" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property integer $activo
 * @property string $nombrecompleto
 *
 */
abstract class BaseUsuario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'adm_usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuario|Usuarios', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, password', 'required'),
			array('activo', 'numerical', 'integerOnly'=>true),
			array('username', 'length', 'max'=>30),
			array('password', 'length', 'max'=>128),
			array('nombrecompleto', 'length', 'max'=>100),
			array('activo, nombrecompleto', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, username, password, activo, nombrecompleto', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'activo' => Yii::t('app', 'Activo'),
			'nombrecompleto' => Yii::t('app', 'Nombrecompleto'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('activo', $this->activo);
		$criteria->compare('nombrecompleto', $this->nombrecompleto, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        public function validatePassword($password) {
         return $this->hashPassword($password) === $this->password;
    }
    public function hashPassword($password) {
        return md5($password);
    }
}