<?php

/**
 * This is the model base class for the table "inst_secretaria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Secretaria".
 *
 * Columns in table "inst_secretaria" available as properties of the model,
 * followed by relations of table "inst_secretaria" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $departamento
 * @property string $tipo
 * @property string $direccion
 * @property integer $indicativo
 * @property string $telefono1
 * @property string $telefono2
 * @property string $fax
 * @property string $ciudad
 *
 * @property InstEstablecimiento[] $instEstablecimientos
 */
abstract class BaseSecretaria extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_secretaria';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Secretaria|Secretarias', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('indicativo', 'numerical', 'integerOnly'=>true),
			array('nombre, departamento, tipo, ciudad', 'length', 'max'=>25),
			array('direccion, telefono1, telefono2, fax', 'length', 'max'=>100),
			array('departamento, tipo, direccion, indicativo, telefono1, telefono2, fax, ciudad', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, departamento, tipo, direccion, indicativo, telefono1, telefono2, fax, ciudad', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instEstablecimientos' => array(self::HAS_MANY, 'InstEstablecimiento', 'secretariaID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'departamento' => Yii::t('app', 'Departamento'),
			'tipo' => Yii::t('app', 'Tipo'),
			'direccion' => Yii::t('app', 'Direccion'),
			'indicativo' => Yii::t('app', 'Indicativo'),
			'telefono1' => Yii::t('app', 'Telefono1'),
			'telefono2' => Yii::t('app', 'Telefono2'),
			'fax' => Yii::t('app', 'Fax'),
			'ciudad' => Yii::t('app', 'Ciudad'),
			'instEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('departamento', $this->departamento, true);
		$criteria->compare('tipo', $this->tipo, true);
		$criteria->compare('direccion', $this->direccion, true);
		$criteria->compare('indicativo', $this->indicativo);
		$criteria->compare('telefono1', $this->telefono1, true);
		$criteria->compare('telefono2', $this->telefono2, true);
		$criteria->compare('fax', $this->fax, true);
		$criteria->compare('ciudad', $this->ciudad, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}