<?php

/**
 * This is the model base class for the table "inst_tipo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tipo".
 *
 * Columns in table "inst_tipo" available as properties of the model,
 * followed by relations of table "inst_tipo" available as properties of the model.
 *
 * @property integer $id
 * @property string $tipo
 *
 * @property InstEstablecimiento[] $instEstablecimientos
 */
abstract class BaseTipo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_tipo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tipo|Tipos', $n);
	}

	public static function representingColumn() {
		return 'tipo';
	}

	public function rules() {
		return array(
			array('tipo', 'length', 'max'=>25),
			array('tipo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, tipo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instEstablecimientos' => array(self::HAS_MANY, 'InstEstablecimiento', 'tipoID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tipo' => Yii::t('app', 'Tipo'),
			'instEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('tipo', $this->tipo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}