<?php

/**
 * This is the model base class for the table "historicoacademicosuperior".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Historicoacademicosuperior".
 *
 * Columns in table "historicoacademicosuperior" available as properties of the model,
 * followed by relations of table "historicoacademicosuperior" available as properties of the model.
 *
 * @property integer $id
 * @property string $tipotitulo
 * @property string $fechainicio
 * @property string $fechafin
 * @property string $titulo
 * @property integer $estado
 * @property integer $egresadoID
 * @property integer $InstEduID
 *
 * @property InstEduSup $egresado
 */
abstract class BaseHistoricoacademicosuperior extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'historicoacademicosuperior';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Historicoacademicosuperior|Historicoacademicosuperiors', $n);
	}

	public static function representingColumn() {
		return 'tipotitulo';
	}

	public function rules() {
		return array(
			array('estado, egresadoID, InstEduID', 'numerical', 'integerOnly'=>true),
			array('tipotitulo', 'length', 'max'=>25),
			array('titulo', 'length', 'max'=>40),
			array('fechainicio, fechafin', 'safe'),
			array('tipotitulo, fechainicio, fechafin, titulo, estado, egresadoID, InstEduID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, tipotitulo, fechainicio, fechafin, titulo, estado, egresadoID, InstEduID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'egresado' => array(self::BELONGS_TO, 'InstEduSup', 'egresadoID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tipotitulo' => Yii::t('app', 'Tipo titulo'),
			'fechainicio' => Yii::t('app', 'Fecha inicio'),
			'fechafin' => Yii::t('app', 'Fecha fin'),
			'titulo' => Yii::t('app', 'Titulo'),
			'estado' => Yii::t('app', 'Estado'),
			'egresadoID' => null,
			'InstEduID' => Yii::t('app', 'Inst Edu'),
                         'nombreinstituto' => Yii::t('app', 'Nombre institución'),
			'egresado' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('tipotitulo', $this->tipotitulo, true);
		$criteria->compare('fechainicio', $this->fechainicio, true);
		$criteria->compare('fechafin', $this->fechafin, true);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('estado', $this->estado);
		$criteria->compare('egresadoID', $this->egresadoID);
		$criteria->compare('InstEduID', $this->InstEduID);
                $criteria->compare('nombreinstituto',  $this->nombreinstituto);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}