<?php

/**
 * This is the model base class for the table "inst_sector".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sector".
 *
 * Columns in table "inst_sector" available as properties of the model,
 * followed by relations of table "inst_sector" available as properties of the model.
 *
 * @property integer $id
 * @property string $sector
 *
 * @property InstEstablecimiento[] $instEstablecimientos
 */
abstract class BaseSector extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_sector';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Sector|Sectors', $n);
	}

	public static function representingColumn() {
		return 'sector';
	}

	public function rules() {
		return array(
			array('sector', 'length', 'max'=>15),
			array('sector', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, sector', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instEstablecimientos' => array(self::HAS_MANY, 'InstEstablecimiento', 'sectorID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'sector' => Yii::t('app', 'Sector'),
			'instEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('sector', $this->sector, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}