<?php

/**
 * This is the model base class for the table "inst_establecimiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Establecimiento".
 *
 * Columns in table "inst_establecimiento" available as properties of the model,
 * followed by relations of table "inst_establecimiento" available as properties of the model.
 *
 * @property integer $id
 * @property integer $secretariaID
 * @property integer $coddepto
 * @property integer $codmunicipio
 * @property string $codigo
 * @property string $nombre
 * @property string $direccion
 * @property string $telefono
 * @property integer $tipoID
 * @property integer $sectorID
 * @property integer $zonaID
 * @property integer $jornadasestablecimientoID
 * @property integer $nivelesestablecimientoID
 
 * @property string $modeloseducativos
 * @property string $capacidadesexcepcionales
 * @property string $discapacidades
 * @property string $idiomas
 * @property integer $estadoID
 * @property string $calendario
 * @property string $correoelectronico
 * @property string $coord_yx
 * @property InstCapacidadexcepcionalEstablecimiento[] $instCapacidadexcepcionalEstablecimientos
 * @property InstDiscapacidadEstablecimiento[] $instDiscapacidadEstablecimientos
 * @property Municipio $codmunicipio0
 * @property InstEstado $estado
 * @property Departamento $coddepto0
 * @property InstSecretaria $secretaria
 * @property InstSector $sector
 * @property InstTipo $tipo
 * @property InstZona $zona
 * @property InstGradoEstablecimiento[] $instGradoEstablecimientos
 * @property InstHistoricorectores[] $instHistoricorectores
 * @property InstIdiomaEstablecimiento[] $instIdiomaEstablecimientos
 * @property InstJornadaEstablecimiento[] $instJornadaEstablecimientos
 * @property InstModeloseducativosEstablecimiento[] $instModeloseducativosEstablecimientos
 * @property InstNivelEstablecimiento[] $instNivelEstablecimientos
 * @property SedSede[] $sedSedes
 */
abstract class BaseEstablecimiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_establecimiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Establecimiento|Establecimientos', $n);
	}

	public static function representingColumn() {
		return 'codigo';
	}

	public function rules() {
		return array(
			
			array('secretariaID, coddepto, codmunicipio, tipoID, sectorID, zonaID, jornadasestablecimientoID, nivelesestablecimientoID, estadoID', 'numerical', 'integerOnly'=>true),
			array('codigo', 'length', 'max'=>20),
			array('nombre, correoelectronico', 'length', 'max'=>100),
                        array('coord_xy', 'length', 'max'=>200),
			array('direccion', 'length', 'max'=>150),
			array('telefono', 'length', 'max'=>42),
			array('grados', 'length', 'max'=>80),
			array('calendario', 'length', 'max'=>1),
			array('modeloseducativos, capacidadesexcepcionales, discapacidades, idiomas', 'safe'),
			array('secretariaID, coddepto, codmunicipio, codigo, nombre, direccion, telefono, tipoID, sectorID, jornadasestablecimientoID, nivelesestablecimientoID, modeloseducativos, capacidadesexcepcionales, discapacidades, idiomas, estadoID, calendario, correoelectronico, coord_xy', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, secretariaID, coddepto, codmunicipio, codigo, nombre, direccion, telefono, tipoID, sectorID, zonaID, jornadasestablecimientoID, nivelesestablecimientoID,  modeloseducativos, capacidadesexcepcionales, discapacidades, idiomas, estadoID, calendario, correoelectronico, coord_xy', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instCapacidadexcepcionalEstablecimientos' => array(self::HAS_MANY, 'InstCapacidadexcepcionalEstablecimiento', 'establecimientoID'),
			'instDiscapacidadEstablecimientos' => array(self::HAS_MANY, 'InstDiscapacidadEstablecimiento', 'establecimientoID'),
			'codmunicipio0' => array(self::BELONGS_TO, 'Municipio', 'codmunicipio'),
			'estado' => array(self::BELONGS_TO, 'Estado', 'estadoID'),
			'coddepto0' => array(self::BELONGS_TO, 'Departamento', 'coddepto'),
			'secretaria' => array(self::BELONGS_TO, 'Secretaria', 'secretariaID'),
			'sector' => array(self::BELONGS_TO, 'Sector', 'sectorID'),
			'tipo' => array(self::BELONGS_TO, 'Tipo', 'tipoID'),
			'zona' => array(self::BELONGS_TO, 'Zona', 'zonaID'),
			'instGradoEstablecimientos' => array(self::HAS_MANY, 'InstGradoEstablecimiento', 'establecimientoID'),
			'instHistoricorectores' => array(self::HAS_MANY, 'InstHistoricorectores', 'establecimientoID'),
			'instIdiomaEstablecimientos' => array(self::HAS_MANY, 'InstIdiomaEstablecimiento', 'establecimientoID'),
			//'instJornadaEstablecimientos' => array(self::HAS_MANY, 'instJornadaEstablecimiento', 'establecimientoID'),
			'instModeloseducativosEstablecimientos' => array(self::HAS_MANY, 'InstModeloseducativosEstablecimiento', 'establecimientoID'),
			'instNivelEstablecimientos' => array(self::HAS_MANY, 'InstNivelEstablecimiento', 'establecimientoID'),
			'sedSedes' => array(self::HAS_MANY, 'SedSede', 'establecimientoID'),
                        //'instsecretaria' => array(self::BELONGS_TO, 'InstSecretaria', 'secretariaID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'secretariaID' =>  Yii::t('app', 'Secretaría'),
                        'secretaria' => null,
			'coddepto' => null,
			'codmunicipio' =>  Yii::t('app', 'Municipio'),
                        'nom_municipio' =>  Yii::t('app', 'Municipio'),
			'codigo' => Yii::t('app', 'Código'),
			'nombre' => Yii::t('app', 'Nombre'),
			'direccion' => Yii::t('app', 'Dirección'),
			'telefono' => Yii::t('app', 'Teléfono'),
			'tipoID' => null,
			'sectorID' => null,
			'zonaID' => null,
			'jornadasestablecimientoID' => Yii::t('app', 'Jornadasestablecimiento'),
                        'jornadas' => Yii::t('app', 'Jornadas'),
			'nivelesestablecimientoID' => Yii::t('app', 'Nivelesestablecimiento'),
			'grados' => Yii::t('app', 'Grados'),
			'modeloseducativos' => Yii::t('app', 'Modelos educativos'),
			'capacidadesexcepcionales' => Yii::t('app', 'Capacidades excepcionales'),
			'discapacidades' => Yii::t('app', 'Discapacidades'),
			'idiomas' => Yii::t('app', 'Idiomas'),
			'estadoID' => null,
			'calendario' => Yii::t('app', 'Calendario (A o B)'),
			'correoelectronico' => Yii::t('app', 'Correoelectronico'),
			'instCapacidadexcepcionalEstablecimientos' => null,
			'instDiscapacidadEstablecimientos' => null,
			'codmunicipio0' => null,
			'estado' => null,
			'coddepto0' => null,
			'secretaria' => null,
			'sector' => null,
			'tipo' => null,
			'zona' => null,
			'instGradoEstablecimientos' => null,
			'instHistoricorectores' => null,
			'instIdiomaEstablecimientos' => null,
			//'instJornadaEstablecimientos' => null,
			'instModeloseducativosEstablecimientos' => null,
			'instNivelEstablecimientos' => null,
			'sedSedes' => null,
                        'nombre_rector' => Yii::t('app', 'Rector'),
                        'coord_xy' => Yii::t('app', 'Coordenadas'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('secretariaID', $this->secretariaID);
                $criteria->compare('secretaria', $this->secretaria);
		$criteria->compare('coddepto', $this->coddepto);
                $criteria->compare('nom_depto', $this->nom_depto);
		$criteria->compare('codmunicipio', $this->codmunicipio);
                $criteria->compare('nom_municipio', $this->nom_municipio);
		$criteria->compare('codigo', $this->codigo, true);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('direccion', $this->direccion, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('tipoID', $this->tipoID);
		$criteria->compare('sectorID', $this->sectorID);
		$criteria->compare('zonaID', $this->zonaID);
		$criteria->compare('jornadasestablecimientoID', $this->jornadasestablecimientoID);
                $criteria->compare('jornadas', $this->jornadas);
		$criteria->compare('nivelesestablecimientoID', $this->nivelesestablecimientoID);
                $criteria->compare('niveles', $this->niveles);
		$criteria->compare('grados', $this->grados);
		$criteria->compare('modeloseducativos', $this->modeloseducativos, true);
		$criteria->compare('capacidadesexcepcionales', $this->capacidadesexcepcionales, true);
		$criteria->compare('discapacidades', $this->discapacidades, true);
		$criteria->compare('idiomas', $this->idiomas, true);
		$criteria->compare('estadoID', $this->estadoID);
                $criteria->compare('estado', $this->estado);
		$criteria->compare('calendario', $this->calendario, true);
		$criteria->compare('correoelectronico', $this->correoelectronico, true);
                $criteria->compare('nombre_rector', $this->nombre_rector, true);
                $criteria->compare('coord_xy', $this->coord_xy, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}