<?php

/**
 * This is the model base class for the table "municipio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Municipio".
 *
 * Columns in table "municipio" available as properties of the model,
 * and there are no model relations.
 *
 * @property double $idmunicipio
 * @property string $nombre
 * @property double $codigo
 * @property double $poblacion
 * @property double $departamento_id
 *
 */
abstract class BaseMunicipio extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'municipio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Municipio|Municipios', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('idmunicipio, codigo, poblacion, departamento_id', 'numerical'),
			array('nombre', 'length', 'max'=>240),
			array('idmunicipio, nombre, codigo, poblacion, departamento_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idmunicipio, nombre, codigo, poblacion, departamento_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
                    'egresados' => array(self::HAS_MANY, 'Egresado', 'MUNICIPIO_NACIMIENTO_ID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idmunicipio' => Yii::t('app', 'Idmunicipio'),
			'nombre' => Yii::t('app', 'Nombre'),
			'codigo' => Yii::t('app', 'Codigo'),
			'poblacion' => Yii::t('app', 'Poblacion'),
			'departamento_id' => Yii::t('app', 'Departamento'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idmunicipio', $this->idmunicipio);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('codigo', $this->codigo);
		$criteria->compare('poblacion', $this->poblacion);
		$criteria->compare('departamento_id', $this->departamento_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}