<?php

/**
 * This is the model base class for the table "inst_grado_establecimiento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GradoEstablecimiento".
 *
 * Columns in table "inst_grado_establecimiento" available as properties of the model,
 * followed by relations of table "inst_grado_establecimiento" available as properties of the model.
 *
 * @property integer $id
 * @property integer $establecimientoID
 * @property integer $gradoID
 *
 * @property InstEstablecimiento $establecimiento
 * @property InstGrado $grado
 */
abstract class BaseGradoEstablecimiento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_grado_establecimiento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GradoEstablecimiento|GradoEstablecimientos', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('establecimientoID, gradoID', 'numerical', 'integerOnly'=>true),
			array('establecimientoID, gradoID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, establecimientoID, gradoID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'establecimiento' => array(self::BELONGS_TO, 'InstEstablecimiento', 'establecimientoID'),
			'grado' => array(self::BELONGS_TO, 'InstGrado', 'gradoID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'establecimientoID' => null,
			'gradoID' => null,
			'establecimiento' => null,
			'grado' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('establecimientoID', $this->establecimientoID);
		$criteria->compare('gradoID', $this->gradoID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}