<?php

/**
 * This is the model base class for the table "inst_zona".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Zona".
 *
 * Columns in table "inst_zona" available as properties of the model,
 * followed by relations of table "inst_zona" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombrezona
 *
 * @property InstEstablecimiento[] $instEstablecimientos
 */
abstract class BaseZona extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_zona';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Zona|Zonas', $n);
	}

	public static function representingColumn() {
		return 'nombrezona';
	}

	public function rules() {
		return array(
			array('nombrezona', 'length', 'max'=>20),
			array('nombrezona', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombrezona', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instEstablecimientos' => array(self::HAS_MANY, 'InstEstablecimiento', 'zonaID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombrezona' => Yii::t('app', 'Nombrezona'),
			'instEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombrezona', $this->nombrezona, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}