<?php

/**
 * This is the model base class for the table "inst_estado".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Estado".
 *
 * Columns in table "inst_estado" available as properties of the model,
 * followed by relations of table "inst_estado" available as properties of the model.
 *
 * @property integer $id
 * @property string $estado
 *
 * @property InstEstablecimiento[] $instEstablecimientos
 */
abstract class BaseEstado extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inst_estado';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Estado|Estados', $n);
	}

	public static function representingColumn() {
		return 'estado';
	}

	public function rules() {
		return array(
			array('estado', 'required'),
			array('estado', 'length', 'max'=>20),
			array('id, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'instEstablecimientos' => array(self::HAS_MANY, 'InstEstablecimiento', 'estadoID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'estado' => Yii::t('app', 'Estado'),
			'instEstablecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('estado', $this->estado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}